{% set version = "1.3-10" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hsaur
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/HSAUR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/HSAUR/HSAUR_{{ version }}.tar.gz
  sha256: 2bee39d5d711054e0ab42abc718eb7e8fc17324c36a7d096f376953496ca8dfc

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('HSAUR')"           # [not win]
    - "\"%R%\" -e \"library('HSAUR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=HSAUR
  license: GPL-2.0-or-later
  summary: Functions, data sets, analyses and examples from the book  ''A Handbook of Statistical Analyses Using R'' (Brian S. Everitt and Torsten Hothorn, Chapman & Hall/CRC, 2006). The first chapter of the book, which is entitled ''An Introduction to R'',  is completely included in this package, for all other chapters,
    a vignette containing all data analyses is available.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
