travis:
  secure:
    BINSTAR_TOKEN: C94ELcXWo1dvSTUDhOQIKMeQFPvtphBadI9JH30iqUrV6GmE/DJ+7bzj4QzIVrYVFrJDh9DMHc9cWcnUm+mbEmC3Ltr+8UqtCL2xNULuyLP0VaNU31zy+kEw4TBYAKYm1KJVZuGBKh337wPy0QPcrs7TBjS7SzCDmYo6ZiJgUAExSGC/M8tvVj6P3H0QwFeWz15TT8vhvtdqVwz5xdS9K1a/D9g4HGK0N5zND5p3FaLw7d+Z3bFTJf35029HqtHS4BJtCusXTzqLWkkxN+qUcXGb0fG4nK5nEUKLpAVg/vayhk4LNPsejl+gxdruxbl2NNtlymYJquzM9acd8gqhY9o1Vxl/Z22Kww1w5AxUkPbvo1GLcdZ05q8EOnfhI1Hu2IUPoIf21ID/zj++8hlK08/u17iqW87KKAzhJTjqR48P57/CF1SK5F4AXyxb6Ga2QkTwM/7HAa4RdiZ81UksBhbl3iOO/VavH4ZtciUPCP9FHrLX/DAWEcFws/NRA5YN1wj1jlBtvpYGBhj6Bkz/+lHao1iT7z7a5TvsLoJmd69RF9Nnlvo5pa1f3brXTAFCOdjn4t0txa8P4DEHUgyGjsJWowIolLhr9o7T05WznVu9gD9Ik0HPCyL3EvUKJVSrwBD3mTeVMkWKminjPFkt4tP/X8V6lm/hWEMXDb6d6jc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
