travis:
  secure:
    BINSTAR_TOKEN: ag7sLfmSFGu6ald0YYFTwQimKORChktpra8s7rItSW0uIovYiH/Z2wZQ4WTp3fbaQq3Z36OTe9ogqx+LS4B1n2AuPi+lw3SuW7It+2uSkUAYst782c9g07MdfFhSnErG8iWivFtHC1nVHKWzbULR7ewyje+Mh8HBRzu+ZyvhWIqdyAn1HjuSCkCRbc8qi1q+WwQHjpaVazqUz+DH4a22j5cy8T+nRUcC9hdYdbHiHZ0NfjXcsE6yHhQaZBeHTAIm1CbdaDiK3rh0IEuF86KShmrpQg43KmHDH+WrF+UgZGk0fT6wj+qimlkBhiO6kus5pjaHL4NpKr/b6+uN74rf4wpO8WdPBVTpfCkc7Xn3dRGAW32MYWi3NKpTkpVj2FIa0vrrDXeFeys6XbJ8Q4ag6hS57khfegfkhbjrk4J12EvINpmTC4iGJ4/IznXdBfbrjn1RFtc0k71tfaPc820QO/pZxcBRHqQVeSXFu5Sm9KaV6JjVcXDwNf0/pGVbrQCpwHnhNckzLmr1XkDaTh8oJ7i9AVzkfBSx4Fd0gohOzRqtrVRAy0AJNjs87cb371FTFDBwxk4zZDzYBNpTwOft3EcFpnK3TSoqXuhC2UNiN+GkmKSq1qslDhl1MuGrUuoYXVyO6iGuOaolvmJzQrbg05mBJQkrnKQFN2qmu+USerk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
