travis:
  secure:
    BINSTAR_TOKEN: YQpsaWby4efwrcyC9uiU/iRqMQS9CQPi/blWsWjZ6A8xvpX+6d/rBZF8DyPydj4n3R5pXwg6PA+z2fKOvwk5BXgKdngftcc5bnxHcjZZX40LMhcdM/8M+VVMB8CV7G8v2Plj7H2rvQ41XVF/Y6ywI72RAYk9qnkNjPlJY9mSNge3HKnO0QE1HvUH/P/YcoPkCmuphySWXnZiz5TfTdZnU8T6Z5A23V9rBOZf7ybcnLXyM+QTIwwSwIYeRqrcUbwvs8Fuv9jQz/y7P4vIFV6xQi4iqI/dgRHg5RmE27VO2V2MIYruKesuFoij1EzF/H5O82yku/n58ysjrEfvpPaxiFucEk1+gs0LndaMe4ODEux3w4nf+feGexU1t8LSCJErudHcyqBrji/j70b8vbkZUFAGPHHAo0u++GvqJSDLYq0gf1bllaBNioccGDak9kc5sG+T+NU2OjpDPRFishxZ0lzjF8eBEZ+Ik86R479j98NJrsRJ3yGity1v6ZmNjYntX/K1c01RMS/e9MUY2jDKgvGDCqSGd/xzrYy7/nBfGN5QzWoe9IZoCKxnDeBdwBiB6pUOJ+h0vwZ1VWnhYyh1fTLJNUA69wwF7kuq7aShImhHY6rwwu+qcDydpEfpqhfdbex1kb3xUCa2Ey9XoCR8EK7/uMfjNrM94v21RI5Zb8w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
