appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: qFQAYX1Ch+l09yhy3YMvZ3okzR23+zp69N9UBmDhshAqa3LVKXdj0UYkM51ViSaiPz6FXVx63eLpCipRVJiYDHqS0Aa79meslY2gKspfz0rsT8Sw3lDCEtEyiheiCUK/DJ5p/1o1HyEU3oM9xjn81N2XyviwCH/yIIFIiraCENajBSZ5TvYNfYRlXndS62n4WWvV+B1Yprlk37OwGFRn0PXJ/zxfagX3y/uYpotxQf93/TGIRBImirJLIw8VEArslwfv74yktIDoTO3SH1fAiC0T/0dxgu7burvn5TAwKHHMZKVkm+fK3jzHlujg5XXsteXFtpJeSkkg1cRj7H6PSw465sINSCtDgYFRg9SppkrduCyspGReSFN87BNCgtCxBcSi4ottvW0FFmIGDHUlMvdAuiFik5FjYdbRzbfAmEbLi/jldq1ljFRaS2bYUt78hee65JSzZo02EL1iOi5zPe500x+/4JcSscaTkGSK2FJKRV+beiw0sYVlamZIXutBD6CJe0IRnU27ta2QyXD7w5Wiit2SP+q1Y2cYxEpDylA4HFgZx8GJBwiFU3rke68iMCO8gzTvnr7cM2dWBnDos3TUM/EsUUbUlKhgS5ue9itfXbPkIZNdoTcqt9LfO8D1m3s0DY3BcSNm+ZCd4z0XF0Q27Fm5oI/f0c8GzLSR9sA=}
bot:
  automerge: true
