travis:
  secure:
    BINSTAR_TOKEN: d3HIeZQDoePK57nm9kpBc3+RvIOUSukt8k/yPqwL6pUt8D48W+H/TGNbGMe8uHst+xcsdi4ACVAVqHZphuIZliUhD1hIbvOMyxVJuBEhnoXIa3UgMe6RZTsKprE18AOn1STyUpMG0HBUm9ozBMPsexEWzCVRbFZ53CEtirUMZRjuz9UiBNQl9E3er1RKsvFPh8dqGwv+BRYdCb+gV7mQeQ+jN3JSJ5/CFur2B0xM9XgeZSDvFAVgsfN+cVczA/i4UNdTl7B5cZWbwr6GPX8TtcP5B2NUbE815bltRLOgwGa6DWVneXbg1o49QTpGIhkbXFMZ3lGume8fXyZhiAe0yHqXTbzhJEqPdlwiSS4TwmlWg0rRPoKeOWlhqnkDlqA8QCZIdxxLINkqzJTIQ4rNjqPmFfkreFI98BinyzA8m0BuKzziBpRS14h0fyBAxC27EvpAOWnZtu/+vZwSDJMn1vmtCgOQsNDGg3za1sqPsTfGoTXZyHJdvMgBBu7LChQGvd7J0eTO+/H3DHJifhMpda1jBTAId6YiocMqhaxoGTyKOAs7cZBQzq/s4DUfIonFDsoZ7bqIJXT/hJGKRPoV84rIChN1PHHo9dayQNV7TwhC7k9t7qE9Zd/o/s9vMA9S8Tr6vYS27Pmf3+BXqWR5BDQ9g6OrruBcDAGK+VV1gXs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
